name: Build and Push

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-1
  ECR_REGISTRY: 485141927791.dkr.ecr.eu-west-1.amazonaws.com
  ECR_REPOSITORY: project-7-eks

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout application repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }} \
            .
      - name: scan with trivy
        uses: aquasecurity/trivy-action@v2
        with:
          image-ref: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL'
          ignore-unfixed: true
          vuln-type: 'os,library'
          
      - name: Push Docker image
        run: |
          docker push \
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Checkout GitOps repository
        uses: actions/checkout@v4
        with:
          repository: officialhunter2007-netizen/project-7-gitops
          token: ${{ secrets.GITOPS_TOKEN }}
          path: project-7-gitops

      - name: Update image tag
        run: |
          sed -i "s|image: .*|image: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}|" \
            project-7-gitops/k8s/production/deployment.yaml

      - name: Commit and push GitOps change
        run: |
          cd project-7-gitops

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add k8s/production/deployment.yaml

          git commit -m "Update image to ${{ github.sha }}" || echo "No changes to commit"

          git push

